
cameras:
  # cam0 : 'rtsp://admin:Shazabadmin123@172.16.1.2:554'
  # cam1 : 'rtsp://admin:Shazabadmin123@172.16.1.3:554'
  # cam2 : 'rtsp://admin:Shazabadmin123@172.16.1.4:554'
  # cam3 : 'rtsp://admin:Shazabadmin123@172.16.1.5:554'
  # cam4 : 'rtsp://admin:Shazabadmin123@172.16.1.6:554'
  cam0 : /home/ashish/Videos/server_streams/cam0.mp4
  cam1 : /home/ashish/Videos/server_streams/cam1.mp4
  cam2: /home/ashish/Videos/server_streams/cam2.mp4
  cam3 : /home/ashish/Videos/server_streams/cam3.mp4
  cam4 : /home/ashish/Videos/server_streams/cam4.mp4
  cam5 : /home/ashish/Videos/server_streams/cam5.mp4
  cam6 : /home/ashish/Videos/server_streams/cam6.mp4
  cam7 : /home/ashish/Videos/server_streams/cam7.mp4
  cam8 : /home/ashish/Videos/server_streams/cam8.mp4
  cam9 : /home/ashish/Videos/server_streams/cam9.mp4
  cam10 : /home/ashish/Videos/server_streams/cam10.mp4
  cam11 : /home/ashish/Videos/server_streams/cam11.mp4
  cam12 : /home/ashish/Videos/server_streams/cam12.mp4
  cam13 : /home/ashish/Videos/server_streams/cam13.mp4
  cam14 : /home/ashish/Videos/server_streams/cam14.mp4

models:
  cam0: ['track']
  cam1: ['track']
  cam2: ['track']
  cam3: ['det', 'track']
  cam4: ['det', 'track']
  cam5: ['det', 'gender']
  cam6: ['det', 'track']
  cam7: ['det']
  cam8: ['det', 'gender']
  cam9: ['det', 'gender']
  cam10: ['det', 'gender']
  cam11: ['det', 'gender']
  cam12: ['det', 'gender']
  cam13: ['det', 'track', 'gender', 'weapon']
  cam14: ['det', 'track', 'gender', 'weapon']

camera_status:
  cam0 : 'ON'
  cam1 : 'ON'
  cam2:  'ON'
  cam3 : 'ON'
  cam4 : 'ON'
  cam5 : 'OFF'
  cam6 : 'OFF'
  cam7 : 'OFF'
  cam8 : 'OFF'
  cam9 : 'ON'
  cam10 : 'ON'
  cam11 : 'ON'
  cam12 : 'ON'
  cam13 : 'ON'
  cam14 : 'ON'

ROIs:
  cam0 : []
  cam1 : [[(538, 389), (395, 328), (458, 223), (573, 255)]]
  cam2: [[(208, 8), (307, 8), (314, 166), (223, 163)]]
  cam3 : [[(138, 68), (244, 50), (255, 127), (139, 152)],[(174, 237), (259, 198), (294, 250), (185, 293)], [(295, 257), (307, 291), (200, 333), (187, 296)], [(310, 297), (348, 328), (229, 394), (199, 341)], [(225, 411), (345, 348), (486, 477), (199, 478)]]
  cam4 : []
  cam5 : []
  cam6 : []
  cam7 : []
  cam8 : []
  cam9 : [[(138, 68), (244, 50), (255, 127), (139, 152)],[(174, 237), (259, 198), (294, 250), (185, 293)], [(295, 257), (307, 291), (200, 333), (187, 296)], [(310, 297), (348, 328), (229, 394), (199, 341)], [(225, 411), (345, 348), (486, 477), (199, 478)]]
  cam10 : [[(343, 6), (468, 2), (464, 102), (346, 111)]]
  cam11 : []
  cam12 : []
  cam13 : []
  cam14 : []

POIs:
  cam0 : [x,y]
  cam1 : [x,y]
  cam2: [x,y]
  cam3 : [x,y]
  cam4 : [x,y]
  cam5 : [x,y]
  cam6 : [x,y]
  cam7 : [x,y]
  cam8 : [x,y]
  cam9 : [x,y]
  cam10 : [x,y]
  cam11 : [x,y]
  cam12 : [x,y]
  cam13 : [x,y]
  cam14 : [x,y]


